[build-system]
requires = ["setuptools>=68", "setuptools_scm>=8", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
# e.g., tags: 0.1.2 or v0.1.2
version_scheme = "guess-next-dev"
local_scheme = "no-local-version"
write_to = "lexsiai/version.py"